@Library("shared") _ 
pipeline {
    agent { label "ankith" }
    
    stages {
        
        stage("Hello") {
            steps {
                script {
                    hello()
                }
            }
        }

        stage("Code") {
            steps {
                script {
                    
                    clone("https://github.com/Ankithv007/jenkins.git", "main") 
                }
            }
        }

        stage("Build") {
            steps {
                dir('jen-proj') { 
                    script {
                        docker_build("node-app-test-new", "latest", "ankithbv007")
                    }
                }
            }
        }

        stage("Push to DockerHub") {
            steps {
                dir('jen-proj') { 
                    script {
                        docker_push("node-app-test-new", "latest", "ankithbv007") 
                    }
                }
            }
        }

        stage("Deploy") {
            steps {
                dir('jen-proj') { 
                    echo 'Deploying with Docker Compose'
                    sh "docker compose up -d" 
                }
            }
        }
    }
}
