@Library("shared") _ 
pipeline {
    agent { label "ankith"}
    
    stages {
        
         stage("Hello"){
            steps{
                script{
                    hello()
                }
            }
        }
        stage("Code"){
            steps{
               script{
                clone("https://github.com/Ankithv007/jenkins/tree/main/jen-proj","main")
               }
                
            }
        }
        stage("Build"){
            steps{
                script{
                docker_build("node-app-test-new","latest","ankithbv007")
                }
            }
        }
       stage("Push to DockerHub"){
            steps{
                script{
                    docker_push("node-app-test-new","latest","ankithbv007")
                }
            }
        }
        stage("deploy"){
            steps{
               
                echo 'this is for depoly with compose'
                sh "docker compose up -d"
            }
        }
    }
}
