pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Database') {
      agent {
        docker { image 'mysql:8.0' }
      }
      environment {
        MYSQL_ROOT_PASSWORD = 'Anki@123'   // Set the root password for MySQL
        MYSQL_DATABASE = 'database-1'      // Create a default database
        MYSQL_USER = 'ankith'              // Create a user
        MYSQL_PASSWORD = 'Ankit@098'       // Set the password for the user
      }
      steps {
        sh 'mysql --version'
      }
    }
  }
}
